[package]
name = "jview"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
crossterm = "0.24"
lazy_static = "1.5.0"
log = "0.4.22"
once_cell = "1.20.2"
ratatui = { version = "0.30.0-alpha.0" }
